### ISSUE TITLE
white color issue

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#10]
I think is bug but when turn on white all RGBW come ON and become cold white instead the only W come ON

**Comment by toshibochan** [comment]
my led strip is RGBW is warm white. whit this code (https://github.com/PA7T/magic_home_strip_rgbw) when turn on white only W come on and RGB is off.

**Comment by maccoylton** [comment]
Ok . .this is a design consideration, not a bug .. my need was white equals all LEDs come on ie RGB & W.  This primarily to maximize brightness. You can use the temperature option int he Home app to adjust  the warmth. If that does not meet your need the a different implementation would be required,

**Comment by toshibochan** [comment]
I use the temperature but not get good warm color, still little cold. I wonder if you can add opinion to make only W come on when select white.

**Comment by maccoylton** [comment]
I;d recommend creating a separate accessory for that since it is different logic

**Comment by toshibochan** [comment]
where in the code I have to change?

**Comment by maccoylton** [comment]
>where in the code I have to change?

@toshibochan you would need to decide if you wanted a spectate accessory to show up to control the white leds or what would be the logic of transitioning from colour to white, which would be a complete rewrite of the routine that converts the hsi to rgbw and set the new colour. This is not trivial.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toshibochan** [comment]
I want turn on white and the RGB turn off.

https://github.com/PA7T/magic_home_strip_rgbw
This link do that but light is not stable and i can see light flicking all the time.  I compare PA7T code and yours but I don’t know where to change for control white color.

**Comment by vniehues** [comment]
Did you resolve this issue? @maccoylton @toshibochan

**Comment by toshibochan** [comment]
@vniehues latest firmware is working great. You can chose if you have RGB or RGBW using eve app.

**Comment by vniehues** [comment]
@toshibochan got it, thank you very much!
