### ISSUE TITLE
question.

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#12]
how to upload main.bin to GitHub?

**Comment by maccoylton** [comment]
Create a release in your repository and then upload the files to the release. If unsure how to do that, google how to create a git release 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maccoylton** [comment]
Create a release in your repository and then upload the files to the release. If unsure how to do that, google how to create a git release 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
