### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#13]
You can add a switch in the app to do this change? Same as you can chose gpio pins.
 If want W (white) only come ON
“
    int Bo = (int)(rgbw->blue - Luminance);
    int Ro = (int)(rgbw->red - Luminance);
    int Go = (int)(rgbw->green - Luminance);
/*
int Bo = (int)(rgbw->blue);
int Ro = (int)(rgbw->red);
int Go = (int)(rgbw->green);
*/
“

If want all RGBW (cold white) come ON:
“
/*
    int Bo = (int)(rgbw->blue - Luminance);
    int Ro = (int)(rgbw->red - Luminance);
    int Go = (int)(rgbw->green - Luminance);
*/
int Bo = (int)(rgbw->blue);
int Ro = (int)(rgbw->red);
int Go = (int)(rgbw->green);
“

**Comment by maccoylton** [comment]
implemented pure whte on wil give you just w, pure white off will give you rgb+w
