### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#17]
Sorry I keep asking things!
Can GPIO0 become push Button?
Single press
Double press
Triple press
And hold reset the magichome

**Comment by maccoylton** [comment]
>Sorry I keep asking things! ...

@toshibochan what physical device do you have? None of mine have a physical button?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toshibochan** [comment]
Is just the magichome rgbw controller without IR. I can solder wire to GPIO0 and Ground and add button. Is possible to add code?

**Comment by toshibochan** [comment]
I want add push button because sometimes is good if Siri not working and all is good to have option to turn on manually. And can save money because no need to buy extra wireless hue switch

**Comment by toshibochan** [comment]
I made this lamp using your main.bin and work great! Is cool if have a button to turn on and off manually to.
![0DA86856-D309-4B79-B490-A81F3E35A170](https://user-images.githubusercontent.com/15816913/73140036-29f54c80-4029-11ea-8e77-57f4a41c6b64.jpeg)

**Comment by jihao** [comment]
@toshibochan I did something for my DIY controller which has a button, you may change the pins before use.  

Code here: https://github.com/jihao/esp-homekit-rgbw-strip/tree/dev

**Comment by maccoylton** [comment]
If you are happy this works, why don't you submit a push request to add this to this repo

**Comment by jihao** [comment]
> If you are happy this works, why don't you submit a push request to add this to this repo

Later, I made some tweak which might not be your intention.  
Like turn on the light by increasing the brightness gradually just like philips hue behavior, but not perfect, it will get a slight flicker at the max brightness ...

So maybe I can extract the button feature to a seperate branch, then submit a pull request.

**Comment by maccoylton** [comment]
ok .. no worries

**Comment by toshibochan** [comment]
hi @jihao you can turn on issue page in your https://github.com/jihao/esp-homekit-rgbw-strip/tree/dev.
the clone or download link is not correct.

**Comment by toshibochan** [comment]
Hi @jihao you git clone address not working
