### ISSUE TITLE
still having some error when pairing to home app using your main.bin

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#18]
standard_init:SDK version: 0.9.9, free heap 41360
get_sysparam_info: Sysparam base address 1011712, num_sectors 2
get_sysparam_info: sysparam name: wifi_ssid, value:GTP Airport, key length:9, value length:11
get_sysparam_info: sysparam name: wifi_password, value:**********
get_sysparam_info: sysparam name: ota_repo, value:maccoylton/esp-homekit-rgbw-strip, key length:8, value length:33
get_sysparam_info: sysparam name: ota_file, value:main.bin, key length:8, value length:8
get_sysparam_info: sysparam name: ota_version, value:0.8.5, key length:11, value length:5
get_sysparam_info: while loop status 1
load_characteristic_from_flash: WiFi check interval: int: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
Create accessory name
|manuf='maccoylton' serial='2C:F4:32:B7:E7:89' model='esp-homekit-rgbw-strip' revision='0.8.5' c#=8005
>>> wifi_config: Initializing WiFi config
>>> wifi_config: Connecting to Airport
mode : sta(2c:f4:32:b7:e7:89)
add if0

checkWifiTask WiFi: check interval 200, Status:  default = 1: Free Heap=38372, Free Stack=25
scandone
add 0
aid 1
cnt

connected with Airport, channel 11
dhcp client start...
ip:10.0.1.24,mask:255.255.255.0,gw:10.0.1.1
>>> wifi_config: Connected to WiFi network
on_wifi_ready
get_sysparam_info: Sysparam base address 1011712, num_sectors 2
get_sysparam_info: sysparam name: wifi_ssid, value:Airport, key length:9, value length:11
get_sysparam_info: sysparam name: wifi_password, value:**********
get_sysparam_info: sysparam name: ota_repo, value:maccoylton/esp-homekit-rgbw-strip, key length:8, value length:33
get_sysparam_info: sysparam name: ota_file, value:main.bin, key length:8, value length:8
get_sysparam_info: sysparam name: ota_version, value:0.8.5, key length:11, value length:5
get_sysparam_info: while loop status 1
on_wifi_ready Reset Reason: Soft Reeet
on_wifi_ready: Exception Cause: 0
EPC 1: 0
EPC 2: 0
EPC 3: 0
Exv virtul address: 0
DEPC: 0
Return Address:0
>>> HomeKit: Starting server
>>> HomeKit: Formatting flash at 0x8c000
>>> HomeKit: Generated new accessory ID: 0C:73:50:8C:D8:D2
>>> HomeKit: Generated new accessory key
>>> HomeKit: Configuring mDNS
mDNS announcement: Name=Led_Strip-RGBW-12052361 md=esp-homekit-rgbw-strippv=1.0id=0C:73:50:8C:D8:D2c#=8005s#=1ff=0sf=1ci=5
                                                 sh=pvA4kw== Port=5556 TTL=4500
on_homekit_event: Server initialised, Free Heap=31640
on_homekit_event: Acessory is NOT paired on initialisation, Free Heap=31640
;ld��|�d�|

            �
             d�
               b|����s�b�
                           c��'o�$g'���cp$lbdrl8�o�
                                                       �
                                                         $
                                                          
                                                            
                                                             #g�|��l�
                                                                       c��'o�$��$`�'o
        �dgs�ۓo
                ���dp�g�s�����
                                   
                                    c
                                      '�|䇎x
                                              ��'o��d`�ogl '{���g
                                                                         �� s��'
   ��`{l�c�g'���8|�cl#�nx`c�#�c��og��'�c�ncp~�gl�o��o��g#
                                                                   
                                                                    llxc��`�'��nldo���

           
            �l�؛`�g��'��ۃc
                              
                               �l$l~;l�c�gn��l�go�g���o��gl�c�o'��l�og'��`
 ����`;l�og��|���g��bdpp_task_hdl : 3fff08f0, prio:14, stack:512
pm_task_hdl : 3fff0188, prio:1, stack:176
frc2_timer_task_hdl:0x3fff5388, prio:12, stack:200

ESP-Open-SDK ver: 0.0.1 compiled @ Jan 16 2020 21:58:13
phy ver: 273, pp ver: 8.3

standard_init:SDK version: 0.9.9, free heap 41360
get_sysparam_info: Sysparam base address 1011712, num_sectors 2
get_sysparam_info: sysparam name: wifi_ssid, value: Airport, key length:9, value length:11
get_sysparam_info: sysparam name: wifi_password, value:**********
get_sysparam_info: sysparam name: ota_repo, value:maccoylton/esp-homekit-rgbw-strip, key length:8, value length:33
get_sysparam_info: sysparam name: ota_file, value:main.bin, key length:8, value length:8
get_sysparam_info: sysparam name: ota_version, value:0.8.5, key length:11, value length:5
get_sysparam_info: while loop status 1
load_characteristic_from_flash: WiFi check interval: int: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
Create accessory name
|manuf='maccoylton' serial='2C:F4:32:B7:E7:89' model='esp-homekit-rgbw-strip' revision='0.8.5' c#=8005
>>> wifi_config: Initializing WiFi config
>>> wifi_config: Connecting to GTP Airport
mode : sta(2c:f4:32:b7:e7:89)
add if0

checkWifiTask WiFi: check interval 200, Status:  default = 1: Free Heap=38372, Free Stack=25
scandone
add 0
aid 7
cnt

connected with  Airport, channel 11
dhcp client start...
ip:10.0.1.24,mask:255.255.255.0,gw:10.0.1.1
>>> wifi_config: Connected to WiFi network
on_wifi_ready
get_sysparam_info: Sysparam base address 1011712, num_sectors 2
get_sysparam_info: sysparam name: wifi_ssid, value: Airport, key length:9, value length:11
get_sysparam_info: sysparam name: wifi_password, value:**********
get_sysparam_info: sysparam name: ota_repo, value:maccoylton/esp-homekit-rgbw-strip, key length:8, value length:33
get_sysparam_info: sysparam name: ota_file, value:main.bin, key length:8, value length:8
get_sysparam_info: sysparam name: ota_version, value:0.8.5, key length:11, value length:5
get_sysparam_info: while loop status 1
on_wifi_ready Reset Reason: Default Reset
on_wifi_ready: Exception Cause: 0
EPC 1: 0
EPC 2: 0
EPC 3: 0
Exv virtul address: 0
DEPC: 0
Return Address:0
>>> HomeKit: Starting server
>>> HomeKit: Using existing accessory ID: 0C:73:50:8C:D8:D2
>>> HomeKit: Configuring mDNS
mDNS announcement: Name=Led_Strip-RGBW-12052361 md=esp-homekit-rgbw-strippv=1.0id=0C:73:50:8C:D8:D2c#=8005s#=1ff=0sf=1ci=5
                                                 sh=pvA4kw== Port=5556 TTL=4500
on_homekit_event: Server initialised, Free Heap=31764
on_homekit_event: Acessory is NOT paired on initialisation, Free Heap=31764
>>> HomeKit: Got new client connection: 5 from 10.0.1.37, port 41192
on_homekit_event: Client connected, Free Heap=30208
>>> HomeKit: [Client 5] Pair Setup Step 1/3
>>> HomeKit: [Client 5] Pair Setup Step 2/3
>>> HomeKit: [Client 5] Pair Setup Step 3/3
>>> HomeKit: Added pairing with 13856DE2-8074-4312-BDA3-9D1C52F170A9
on_homekit_event: Pairing added, Free Heap=27096
>>> HomeKit: Configuring mDNS
mDNS announcement: Name=Led_Strip-RGBW-12052361 md=esp-homekit-rgbw-strippv=1.0id=0C:73:50:8C:D8:D2c#=8005s#=1ff=0sf=0ci=5
                                                 sh=pvA4kw== Port=5556 TTL=4500
>>> HomeKit: [Client 5] Successfully paired
>>> HomeKit: [Client 5] Closing client connection
on_homekit_event: Client disconnected, Free Heap=30184
>>> HomeKit: Got new client connection: 5 from 10.0.1.37, port 42216
on_homekit_event: Client connected, Free Heap=30204
>>> HomeKit: [Client 5] Pair Verify Step 1/2
>>> HomeKit: [Client 5] Pair Verify Step 2/2
>>> HomeKit: [Client 5] Found pairing with 13856DE2-8074-4312-BDA3-9D1C52F170A9
on_homekit_event: Client verified, Free Heap=28040
on_homekit_event: Acessory is paired on after client validaiton
get_sysparam_info: Sysparam base address 1011712, num_sectors 2
get_sysparam_info: sysparam name: wifi_ssid, value:GTP Airport, key length:9, value length:11
get_sysparam_info: sysparam name: wifi_password, value:**********
get_sysparam_info: sysparam name: ota_repo, value:maccoylton/esp-homekit-rgbw-strip, key length:8, value length:33
get_sysparam_info: sysparam name: ota_file, value:main.bin, key length:8, value length:8
get_sysparam_info: sysparam name: ota_version, value:0.8.5, key length:11, value length:5
get_sysparam_info: while loop status 1
accessory_init: GPIOS are set as follows : W=15, R=12, G=5, B=13
load_characteristic_from_flash: WHITE GPIO: int8: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: RED GPIO: int8: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: GREEN GPIO: int8: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: BLUE GPIO: int8: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
PWM Stopped 0
rgbw_lights_init: Set gpios as follows : W=15, R=12, G=5, B=13
load_characteristic_from_flash: Saturation: float: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: Hue: float: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: Brightness: int: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: Pure White: bool: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
rgbw_lights_init: sdk_os_timer_Setfn called
>>> HomeKit: [Client 5] Verification successful, secure session established

rgbw_set
rgbw_set: Current colour before set r=0,g=0, b=0, w=0,
rgbw_set: led srtip off
PWM Stopped 45088
rgbw_set:Current colour after set r=0,g=0, b=0, w=0,
>>> HomeKit: [Client 5] Get Accessories
>>> HomeKit: [Client 5] Update Characteristics
>>> HomeKit: [Client 5] Add Pairing
>>> HomeKit: Added pairing with 0320352C-C8C2-4DF4-9F99-F57FD1FE9ECD
on_homekit_event: Pairing added, Free Heap=24296
>>> HomeKit: [Client 5] Update Characteristics
>>> HomeKit: [Client 5] Get Characteristics
>>> HomeKit: [Client 5] Get Characteristics
>>> HomeKit: [Client 5] Update Characteristics
Identify
>>> HomeKit: [Client 5] Get Characteristics
>>> HomeKit: [Client 5] Get Characteristics
>>> HomeKit: [Client 5] Get Characteristics
>>> HomeKit: [Client 5] Get Characteristics
>>> HomeKit: Got new client connection: 6 from 10.0.1.197, port 16636
on_homekit_event: Client connected, Free Heap=23168
>>> HomeKit: [Client 6] Pair Verify Step 1/2
>>> HomeKit: [Client 6] Pair Verify Step 2/2
>>> HomeKit: [Client 6] Found pairing with 13856DE2-8074-4312-BDA3-9D1C52F170A9
on_homekit_event: Client verified, Free Heap=21040
>>> HomeKit: [Client 6] Verification successful, secure session established
>>> HomeKit: [Client 6] Get Accessories
>>> HomeKit: [Client 6] Update Characteristics
>>> HomeKit: [Client 6] Update Characteristics
>>> HomeKit: Got new client connection: 7 from 10.0.1.3, port 54006
on_homekit_event: Client connected, Free Heap=20692
>>> HomeKit: [Client 7] Pair Verify Step 1/2
>>> HomeKit: [Client 7] Pair Verify Step 2/2
>>> HomeKit: [Client 7] Found pairing with 0320352C-C8C2-4DF4-9F99-F57FD1FE9ECD
on_homekit_event: Client verified, Free Heap=19004
>>> HomeKit: [Client 7] Verification successful, secure session established
>>> HomeKit: [Client 7] Get Accessories
>>> HomeKit: [Client 5] Get Characteristics
>>> HomeKit: [Client 7] Update Characteristics
>>> HomeKit: [Client 7] Add Pairing
>>> HomeKit: Device Public Key not needing updated
>>> HomeKit: Updated pairing with 13856DE2-8074-4312-BDA3-9D1C52F170A9
>>> HomeKit: [Client 5] Update Characteristics
Identify
>>> HomeKit: Got new client connection: 8 from 10.0.1.35, port 65486
on_homekit_event: Client connected, Free Heap=18584
>>> HomeKit: [Client 8] Pair Verify Step 1/2
>>> HomeKit: [Client 8] Pair Verify Step 2/2
>>> HomeKit: [Client 8] Found pairing with 0320352C-C8C2-4DF4-9F99-F57FD1FE9ECD
on_homekit_event: Client verified, Free Heap=14488
>>> HomeKit: [Client 8] Verification successful, secure session established
>>> HomeKit: Got new client connection: 9 from 10.0.1.198, port 20424
on_homekit_event: Client connected, Free Heap=14092
>>> HomeKit: Got new client connection: 10 from 10.0.1.167, port 19152
on_homekit_event: Client connected, Free Heap=12732
>>> HomeKit: [Client 9] Pair Verify Step 1/2
>>> HomeKit: Got new client connection: 11 from 10.0.1.42, port 29183
on_homekit_event: Client connected, Free Heap=10936
>>> HomeKit: [Client 10] Pair Verify Step 1/2
>>> HomeKit: [Client 8] Get Accessories
rm match
>>> HomeKit: Got new client connection: 12 from ?.?.?.?, port 16383
>>> HomeKit: Error in geetpeername homekit_server_close_old_duplicate_connection

>>> HomeKit: Error in geetpeername homekit_server_close_old_duplicate_connection

>>> HomeKit: Error in geetpeername homekit_server_close_old_duplicate_connection

>>> HomeKit: Error in geetpeername homekit_server_close_old_duplicate_connection

>>> HomeKit: Error in geetpeername homekit_server_close_old_duplicate_connection

>>> HomeKit: Error in geetpeername homekit_server_close_old_duplicate_connection

>>> HomeKit: Error in geetpeername homekit_server_close_old_duplicate_connection

on_homekit_event: Client connected, Free Heap=13316
>>> HomeKit: [Client 11] Pair Verify Step 1/2
>>> HomeKit: [Client 10] Pair Verify Step 2/2
>>> HomeKit: [Client 10] Found pairing with 0320352C-C8C2-4DF4-9F99-F57FD1FE9ECD
on_homekit_event: Client verified, Free Heap=12956
>>> HomeKit: [Client 10] Verification successful, secure session established
!!! HomeKit: [Client 9] Error reading data from socket (code 113). Disconnecting
!!! HomeKit: [Client 8] Error reading data from socket (code 113). Disconnecting
!!! HomeKit: [Client 7] Error reading data from socket (code 113). Disconnecting
!!! HomeKit: [Client 6] Error reading data from socket (code 113). Disconnecting
!!! HomeKit: [Client 5] Error reading data from socket (code 113). Disconnecting
>>> HomeKit: [Client 9] Closing client connection
on_homekit_event: Client disconnected, Free Heap=13552
>>> HomeKit: [Client 8] Closing client connection
on_homekit_event: Client disconnected, Free Heap=15376
>>> HomeKit: [Client 7] Closing client connection
on_homekit_event: Client disconnected, Free Heap=17152
>>> HomeKit: [Client 6] Closing client connection
on_homekit_event: Client disconnected, Free Heap=18936
>>> HomeKit: [Client 5] Closing client connection
on_homekit_event: Client disconnected, Free Heap=20712
>>> HomeKit: [Client 12] Pair Verify Step 1/2
reconnect
!!! HomeKit: [Client 11] Error reading data from socket (code 128). Disconnecting
!!! HomeKit: [Client 10] Error reading data from socket (code 128). Disconnecting
>>> HomeKit: [Client 11] Closing client connection
on_homekit_event: Client disconnected, Free Heap=22244
>>> HomeKit: [Client 10] Closing client connection
on_homekit_event: Client disconnected, Free Heap=24068
!!! HomeKit: [Client 12] Error reading data from socket (code 128). Disconnecting
>>> HomeKit: [Client 12] Closing client connection
on_homekit_event: Client disconnected, Free Heap=25764
scandone
add 0
aid 1
cnt

connected with Airport, channel 11
dhcp client start...
ip:10.0.1.24,mask:255.255.255.0,gw:10.0.1.1
>>> HomeKit: Got new client connection: 5 from 10.0.1.37, port 44008
on_homekit_event: Client connected, Free Heap=25000
>>> HomeKit: [Client 5] Pair Verify Step 1/2
>>> HomeKit: [Client 5] Pair Verify Step 2/2
>>> HomeKit: [Client 5] Found pairing with 13856DE2-8074-4312-BDA3-9D1C52F170A9
on_homekit_event: Client verified, Free Heap=22996
>>> HomeKit: [Client 5] Verification successful, secure session established
>>> HomeKit: [Client 5] Get Accessories
>>> HomeKit: [Client 5] Get Characteristics
>>> HomeKit: [Client 5] Update Characteristics
>>> HomeKit: Got new client connection: 6 from 10.0.1.42, port 31487
on_homekit_event: Client connected, Free Heap=22988
>>> HomeKit: [Client 6] Pair Verify Step 1/2
>>> HomeKit: Got new client connection: 7 from 10.0.1.43, port 52424
on_homekit_event: Client connected, Free Heap=19344
>>> HomeKit: [Client 7] Pair Verify Step 1/2
>>> HomeKit: [Client 6] Pair Verify Step 2/2
>>> HomeKit: [Client 6] Found pairing with 0320352C-C8C2-4DF4-9F99-F57FD1FE9ECD
on_homekit_event: Client verified, Free Heap=18924
>>> HomeKit: [Client 6] Verification successful, secure session established
>>> HomeKit: [Client 7] Pair Verify Step 2/2
>>> HomeKit: [Client 7] Found pairing with 0320352C-C8C2-4DF4-9F99-F57FD1FE9ECD
on_homekit_event: Client verified, Free Heap=19036
>>> HomeKit: [Client 7] Verification successful, secure session established
>>> HomeKit: [Client 6] Get Accessories
>>> HomeKit: [Client 7] Get Accessories
>>> HomeKit: Got new client connection: 8 from 10.0.1.12, port 53199
on_homekit_event: Client connected, Free Heap=18916
>>> HomeKit: [Client 8] Pair Verify Step 1/2
>>> HomeKit: [Client 8] Pair Verify Step 2/2
>>> HomeKit: [Client 8] Found pairing with 0320352C-C8C2-4DF4-9F99-F57FD1FE9ECD
on_homekit_event: Client verified, Free Heap=17144
>>> HomeKit: [Client 8] Verification successful, secure session established
>>> HomeKit: [Client 8] Get Accessories

checkWifiTask WiFi: check interval 200, Status: connection ok: Free Heap=19000, Free Stack=25
>>> HomeKit: [Client 5] Update Characteristics
led_on_set: Led on TRUE so setting colour

rgbw_set
rgbw_set: Current colour before set r=0,g=0, b=0, w=0,
i: 0  f: 0.000000  p: 1.000000  q: 1.000000  t: 1.000000
rgbw_set: h=0,s=0,b=100 => r=255,g=255, b=255
rgbw_set: h=0,s=0,b=100 => r=255,g=255, b=255, w=255,
rgbw_set: GPIOS are set as follows : W=15, R=12, G=5, B=13
PWM Stopped 45088
rgbw_set:Current colour after set r=65025,g=65025, b=65025, w=65025,
>>> HomeKit: Got new client connection: 9 from 10.0.1.167, port 19408
on_homekit_event: Client connected, Free Heap=16972
>>> HomeKit: [Client 9] Pair Verify Step 1/2
>>> HomeKit: Got new client connection: 10 from 10.0.1.35, port 3279
on_homekit_event: Client connected, Free Heap=12332
>>> HomeKit: [Client 10] Pair Verify Step 1/2
>>> HomeKit: [Client 9] Pair Verify Step 2/2
>>> HomeKit: [Client 9] Found pairing with 0320352C-C8C2-4DF4-9F99-F57FD1FE9ECD
on_homekit_event: Client verified, Free Heap=11036
>>> HomeKit: [Client 9] Verification successful, secure session established
>>> HomeKit: [Client 10] Pair Verify Step 2/2
>>> HomeKit: [Client 10] Found pairing with 0320352C-C8C2-4DF4-9F99-F57FD1FE9ECD
on_homekit_event: Client verified, Free Heap=12996
>>> HomeKit: [Client 10] Verification successful, secure session established
>>> HomeKit: [Client 9] Get Accessories
>>> HomeKit: [Client 10] Get Accessories
save_characteristics:
save_characteristic_to_flash: On: writing bool value to flash true
save_characteristic_to_flash: Saturation: writing float value to flash 0.000000
save_characteristic_to_flash: Hue: writing float value to flash 0.000000
save_characteristic_to_flash: Brightness: writing int32 value to flash 100
save_characteristic_to_flash: WiFi check interval: writing int32 value to flash 200
save_characteristic_to_flash: Pure White: writing bool value to flash false
>>> HomeKit: [Client 5] Update Characteristics
led_hue_set: timer armed, HUE: 240.000000

**Comment by maccoylton** [comment]
What’s the specific issue you are having, the above log looks fine, it shows the accessory is paired and multiple devices connecting ok. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toshibochan** [comment]
Have this error:

load_characteristic_from_flash: WHITE GPIO: int8: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: RED GPIO: int8: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: GREEN GPIO: int8: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: BLUE GPIO: int8: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
PWM Stopped 0
rgbw_lights_init: Set gpios as follows : W=15, R=12, G=5, B=13
load_characteristic_from_flash: Saturation: float: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: Hue: float: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: Brightness: int: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic
load_characteristic_from_flash: Pure White: bool: load_characteristic_from_flash: Error in sysparams error:1 loading characteristic

And

load_characteristic_from_flash: Error in sysparams error:1 loading characteristic

And

HomeKit: Error in geetpeername homekit_server_close_old_duplicate_connection

And

!!! HomeKit: [Client 10] Error reading data from socket (code 128). Disconnecting

**Comment by maccoylton** [comment]
The last two are network related .. noting to do with the firmware. 

The others just mean that those parameters have never been changed and therefore written, but this is not an issue since the accessory will be using the defaults. 

What is it about the accessory that is not actually working?

**Comment by toshibochan** [comment]
Okay thanks

**Comment by toshibochan** [comment]
Is just difficult to pair. Sometimes pair quickly but most the time take many attempts

**Comment by maccoylton** [comment]
>Is just difficult to pair. Sometimes pair quickly but most the time take many attempts 

@toshibochan this is a known issues with the esp-HomeKit library, various fixes are being tested.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
