### ISSUE TITLE
HomeKit connection issue

### ISSUE THREAD

**Issue by clovertortoise** [maccoylton/esp-homekit-rgbw-strip#2]
Edit: I noticed that the reds and greens were inverse(green displays red/red displays green)

“The setup code is incorrect ”

the code was 111-11-111

I assumed the 8digits in the device name was the code, oops

**Comment by maccoylton** [comment]
I'm working on being able to specify the GPIO for Red/Green/Blue since some of the clone devices have these swapper over. Will publish that soon
