### ISSUE TITLE
having issues installing from OTA

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#20]
having issues installing from OTA. I set to maccoylton/esp-homekit-rgbw-strip and is trying to download version 0.0.0.

![Screen Shot 2020-02-03 at 11 35 18 PM](https://user-images.githubusercontent.com/15816913/73723430-ddbba380-46dd-11ea-96c4-0de8d18ec113.png)

**Comment by maccoylton** [comment]
>having issues installing from OTA. I set to maccoylton/esp-homekit-rgbw-strip and is trying to download version 0.0.0. ...

@toshibochan this look like an issue accessing GitHub. I would recommend you post this into LCM GitHub repository. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maccoylton** [comment]
Did you ever get this resolved?

**Comment by toshibochan** [comment]
Been a while I try I will look later.

**Comment by toshibochan** [comment]
this link otaboot.bin from wiki not good. (https://github.com/HomeACcessoryKid/ota/releases/)
I download otaboot.bin from this and work okay (https://github.com/HomeACcessoryKid/life-cycle-manager/releases/)

**Comment by maccoylton** [comment]
Thanks I've update the wiki

**Comment by toshibochan** [comment]
Did you update the wiki? The wiki look like is the same.

**Comment by maccoylton** [comment]
Yes .. section 2 is quite different :- 

To install the OTA firmware we need to download the following:- bootloader.bin file from here:- https://github.com/maccoylton/esp-homekit-rgbw-strip/release

You then need to erase and flash these three files to your device as follows, I assume here you have esptool.py installed and know how to put you device into flash mode:-

esptool.py -p /dev/cu.usbserial erase_flash esptool.py -p /dev/cu.usbserial erase_flash esptool.py -p /dev/cu.usbserial --baud 230400 write_flash -fs 8m -fm dout -ff 40m 0x0 bootloader.bin

**Comment by toshibochan** [comment]
The link is not working. Is missing “s” on release”s”

https://github.com/maccoylton/esp-homekit-rgbw-strip/release

**Comment by maccoylton** [comment]
Fixed.. thanks
