### ISSUE TITLE
SK6812 support

### ISSUE THREAD

**Issue by dbartelmus** [maccoylton/esp-homekit-rgbw-strip#21]
Digital single pin support?

**Comment by maccoylton** [comment]
This is possible but would be a separate accessory, check this to see if it has that as an option https://github.com/RavenSystem/esp-homekit-devices

**Comment by dbartelmus** [comment]
Possible to mix RGB on 1 pin? Author said that only PWM is supported

**Comment by maccoylton** [comment]
This does not support RGB on 1 wire, that would require creating a new firmware.
