### ISSUE TITLE
issue when lose internet connection

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#23]
issue when lose internet connection. when the device lose internet connection the led turn red and soon after the light turn off.

**Comment by maccoylton** [comment]
That very strange, I’ve never seen that before. I assume a restart fixed that? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toshibochan** [comment]
Maybe is the same as sonoff-basic esp-open-rtos problem?

**Comment by maccoylton** [comment]
It is, the strange part is why the light turns RED. What GPIOs does your module use?

**Comment by toshibochan** [comment]
![D1093B0E-DA3D-48C3-B8C0-A1246B5F3A90](https://user-images.githubusercontent.com/15816913/82704062-a12e9c00-9c29-11ea-8fae-6f2d779cf0ea.png)

**Comment by maccoylton** [comment]
I'm sorry I have not idea what this would happen, Can you provide a log file using udplog-client.
