### ISSUE TITLE
today all my led controllers disconnect from HomeKit

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#25]
today iOS and TV OS and HomePod OS was updated and later tonight all my led controllers keeping disconnecting from HomeKit and rebooting. Some forgot the GPIO setting when come back to homeckit. Anyone have this problem.

**Comment by maccoylton** [comment]
Hi I haven't seen that issue. How many accessories do you run on your network and how many controllers?

**Comment by toshibochan** [comment]
9 magic home led controller, 5 sonoff mini 8 sonoff basic.
but only happening this problem in the led controller.

**Comment by toshibochan** [comment]
maybe because I'm using family sharing and I'm the guest and im the one adding the device?

**Comment by maccoylton** [comment]
How many Mac's/IOS devices using homekit ?

**Comment by toshibochan** [comment]
3 Macs, 2 iPhones 2 iPads

**Comment by maccoylton** [comment]
>3 Macs, 2 iPhones 2 iPads 

@toshibochan I think we are the limits of memory, too many controllers (Mac’s or IOS devices) can take us over the edge. So with the update and device re-pairing that may tips is over the edge. 

There is some work ongoing to maximize memory utilization. The other option is to limit the number of controllers 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toshibochan** [comment]
You mean memory in the controller?

**Comment by maccoylton** [comment]
no the accessories.. .. each controller that connects to an accessory consumes some memory on the accessory
