### ISSUE TITLE
0.9 firmware "Couldn't add Led_Strip-RGBW"

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#27]
I just did clean install on one controller and I'm trying to add to HomeKit but have error.

Couldn't add Led_Strip-RGBW

![Screen Shot 2020-08-08 at 7 56 00 PM](https://user-images.githubusercontent.com/15816913/89723983-40a23600-d9b2-11ea-9a6b-85314a8e1847.png)
![IMG_4278](https://user-images.githubusercontent.com/15816913/89724002-734c2e80-d9b2-11ea-9bed-2dd28a6d3107.PNG)

**Comment by maccoylton** [comment]
Sorry the new version of esp-homekit has fundamentally changed the way memory is managed, it preallocates a lot of stuff, leaving less memory for the accessory. In my case I just update, But in your case sine you reinitialized , and the paring process uses a lot of memory, then it is having an issue.  Reverting to a previous version is the only option till we get to a fix.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toshibochan** [comment]
how to install previous version?

**Comment by toshibochan** [comment]
0.9.1 is good to add to HomeKit. Was very fast to pair. Now I will test if will lose connection.
