### ISSUE TITLE
give me error "The setup code is incorrect."

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#30]
0.9.4　give me "the setup code is incorrect." When try to pair with 111-11-111

**Comment by toshibochan** [comment]
on_homekit_event: Client connected, Free Heap=24624
>>> HomeKit: [Client 1] Pair Setup Step 1/3
>>> HomeKit: [Client 1] Pair Setup Step 2/3
!!! HomeKit: [Client 1] Failed to compute SRP shared secret (code -2)
>>> HomeKit: [Client 1] Pair Setup Step 1/3

**Comment by maccoylton** [comment]
This happens when the accessory runs out of memory and has nothing to do with the code "111-11-111" its to do with the security keys that are calculated during the pairing process.  

Latest version has significant improvements in memory usage and addresses this issues

**Comment by toshibochan** [comment]
@maccoylton 0.9.5 is working great!
Thank you very much!!!!! 👍🏻

**Comment by maccoylton** [comment]
thanks for letting me know :-)
