### ISSUE TITLE
0.9.5 No Response

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#31]
I install the 0.9.5 firmware in 4 devices and was okay for a couple hours but all start showing No Response.

**Comment by toshibochan** [comment]
I can see all the 4 devices is connect to the wifi but show No Response.

**Comment by toshibochan** [comment]
I reboot the device and come back online. I will see if happens all the time.

**Comment by maccoylton** [comment]
I think this is a bug in the latest version of esp-homekit

**Comment by maccoylton** [comment]
I think this is a bug in the latest version of esp-homekit

**Comment by toshibochan** [comment]
Hope be a fix soon
