### ISSUE TITLE
Request physical button 

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#32]
I have requested to add physical button in the programming pin as button to turn ON 100% and OFF white color.

**Comment by toshibochan** [comment]
Because sometimes the device is not responding in homekit. I just want be able to turn on manually with push button directly in the device

**Comment by toshibochan** [comment]
Just want do like sonoff basic button

**Comment by maccoylton** [comment]
What your asking for is a physical on/off switch, this has noting to do with the code, and is something you would have to do for yourself as it wood one very much specific to the device.
