### ISSUE TITLE
new error to build 

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-rgbw-strip#8]
.......
LD build/main.out
./build/shared_functions.a(shared_functions.o):(.text.task_stats_task+0x1c): undefined reference to `uxTaskGetSystemState'
./build/shared_functions.a(shared_functions.o): In function `task_stats_task':
/home/toshi/projects/esp-homekit-rgbw-strip/components/esp-homekit-common-functions/shared_functions/shared_functions.c:248: undefined reference to `uxTaskGetSystemState'
collect2: error: ld returned 1 exit status
/home/toshi/projects/esp-open-rtos/common.mk:232: recipe for target 'build/main.out' failed
make: *** [build/main.out] Error 1
make: Leaving directory '/home/toshi/projects/esp-homekit-rgbw-strip/src'

**Comment by maccoylton** [comment]
That's what I get for not doing make clean each time .. issue in Makefile now fixed
